### ISSUE TITLE
Using backspace does not erase the mask

### ISSUE THREAD

**Issue by M3Rocket** [xornorik/SVPinView#10]
Steps to reproduce:
1. Type in 3 out of 4 (for example) needed characters
2. Press the backspace button
3. Cursor goes back to the third character, but the "mask" character is still there.
![image](https://user-images.githubusercontent.com/3769123/43674023-b75d7e0a-9781-11e8-8eba-92d43a6aad1d.png)

**Comment by xornorik** [comment]
@M3Rocket Not completely clear on the issue here. The single responsibility event when the user taps the backspace/delete button is to clear the contents of the current field and focus on the previous field.

Once the previous field is focused upon, the user can either enter a new digit in its place or hit backspace to clear the existing content.

**Comment by M3Rocket** [comment]
Also, in reading your comment, I left field 4 blank. Because if I didn't, it would have executed "didFinishCallback". Meaning, you can do this with less characters entered to see the problem:
1. Type in 2 out of 4.
2. Cursor is sitting in cell 3.
3. Leave cell 3 empty. Press backspace.
4. Cursor is sitting in cell 2, but the "mask" character is still there eventhough cell 2 is supposed to be blank because of the backspace.

**Comment by xornorik** [comment]
Okay, let's consider the above case - 
In step 3, when we leave the cell 3 empty and hit backspace - it clears the cell 3 (anyway empty) and moves the cursor to cell 2. **It will clear cell 2 only when cell 2 is in focus and you hit backspace**. That's the only way it would maintain it's single responsibility.

Also, if cell 2 is in focus and you type another digit, the existing digit (masked) would get replaced by the new digit that was just entered and the cursor would move to the next field.

**Comment by M3Rocket** [comment]
My two cents: I disagree. I think what you're describing isn't very user friendly. Users expect the backspace to delete one character to the left. Backspace key is not the same as Left Arrow key. It is ONLY behaving this way because you are putting a "space" (which the user cannot really tell and doesn't expect to be there). It is related to issue #11 

When you press backspace, the reasonable thing to do is to clear the index position - 1. In your case, you are using it like a "Delete" key and then "Left Arrow." To users, Backspace means delete one char to the left of the cursor position. If the cursor is in cell 3, I would expect pressing Backspace would delete cell 2 and put the cursor there. If I then Backspace again, it should delete cell 1 and put the cursor there. That's how things work with all keyboard entry.

**Comment by xornorik** [comment]
Closing this for now. Reopen of required.
