### ISSUE TITLE
Backspace at char index 0 results in defocus

### ISSUE THREAD

**Issue by M3Rocket** [xornorik/SVPinView#13]
Hitting backspace while the cursor is in char index 0 position exits the field. I think that is a bug. Most PIN entry will not exit, but actually remain in position index 0 if the backspace key is used there.

**Comment by xornorik** [comment]
Have added a boolean configuration by the name `shouldDismissKeyboardOnEmptyFirstField` to maintain the focus on the first pinField. This is set to false by default.
