### ISSUE TITLE
Swift 4.2 (4.2.1) Update

### ISSUE THREAD

**Issue by ReveelTeam** [xornorik/SVPinView#22]
Using Xcode 10.1 with Swift 4.2.1 (same on Xcode 10 w/ Swift 4.2)

Getting a compile error, which is an easy fix. Basically in ‘SVPinView.swift’ - on line 87, change these 2 uses of ‘UIViewAutoresizing’ to ‘UIView.AutoresizingMask’

... in case anyone needed this and for an update. Thank you for your repo!

**Comment by xornorik** [comment]
@ReveelTeam Thank you for the report. 
@dangthaison91 had raised a PR(#18) for this. Have merged it, will make a release with the changes shortly.

**Comment by lukeirvin** [comment]
It's not working for me for 4.2
