### ISSUE TITLE
app crash after using pastepin() and can you implement wrongstate or refresh view? 

### ISSUE THREAD

**Issue by adika-juniarsa** [xornorik/SVPinView#29]
i'm trying to using pastepin and app crash on this line 

`let textField = collectionView.cellForItem(at: IndexPath(item: index, section: 0))?.viewWithTag(101 + index) as! SVPinField`

also can you make wrong state for next release 

thanks

**Comment by xornorik** [comment]
Hey @adika-juniarsa, what are the steps that led you to the crash? Wasn't able to recreate it at my end. 

Wrong state in the case where the PIN entered is incomplete?

**Comment by xornorik** [comment]
Have introduced an error state in case there is a casting issue
Closing this for lack of further information. 
Thanks.
