### ISSUE TITLE
Show Pin

### ISSUE THREAD

**Issue by wydydygibus** [xornorik/SVPinView#30]
Hi! 
Is there any chance to do "Show Pin" functionality?

**Comment by xornorik** [comment]
Hi @wydydygibus, could you elaborate on what you mean by "Show PIN" functionality? 

There is a method **getPin()**, which returns the entered PIN if it's complete, else it returns an empty string. The responsibility of displaying the PIN (or the error), belongs to the ViewController on which SVPinView resides on. You can refer the [example project](https://github.com/xornorik/SVPinView/blob/master/SVPinView/Example) linked to the repository.
