### ISSUE TITLE
English and Arabic Localization

### ISSUE THREAD

**Issue by nishan-p** [xornorik/SVPinView#31]
I'm using English and Arabic Localization for my app and I have used this Pinview within my app. This is automatically changing the alignment from Left to Right. I do not want the change in the alignment. 

I want to have the same as it is, like first textfield will start from left and last textfield on the right. I want this similar functionality in both English and Arabic.

**Comment by Sobhi-IOS** [comment]
@xornorik can you reslove this issue ?

**Comment by xornorik** [comment]
I had fixed this issue in one of the earlier releases by enforcing the semantic to be left-to-right. 

Could you help me with recreating the issue? I have tried changing the language on the device and also editing the "Application language" field in the scheme; it stayed left-to-right as intended. 

![screenrecord](https://user-images.githubusercontent.com/21356007/77542831-cd999680-6ecc-11ea-91ac-6fce1b4e8614.gif)

**Comment by usamabinattique** [comment]
Can you please pinpoint where the semantics needs to be changed because i am facing the same issue

**Comment by xornorik** [comment]
@usamabinattique I've already changed the semantic to **force a left-to-right entry** and I was able to confirm it by changing the language on the device (gif attached in my previous comment). 

<img width="260" alt="Screenshot 2020-04-11 11 59 38" src="https://user-images.githubusercontent.com/21356007/79037156-43e80980-7bec-11ea-8c67-ecb22ec4b69e.png">

**Could you help me recreate this?**

**Comment by aliakhtar49** [comment]
By changing language at runtime on the same session , **force a left-to-right entry**  will not work
On new relaunch **force a left-to-right entry**  will work

**Comment by xornorik** [comment]
@aliakhtar49 I tried that, also tried editing the scheme and changing the application language from there. Same result i.e it maintains the left-to-right entry. 

![ezgif-2-843061718d06](https://user-images.githubusercontent.com/21356007/79367214-1fcd5500-7f6b-11ea-9579-d05c488bef74.gif)

This is when I relaunch after the language change.

**Comment by aliakhtar49** [comment]
@xornorik By changing language at runtime  (I was referring to in app mechanism we used to change language on button taped irrespective of the system ) where we manually loaded resources our selves

https://stackoverflow.com/questions/31840176/changing-language-on-the-fly-in-swift

**Comment by xornorik** [comment]
@aliakhtar49 Apologies for the late response. 
I understood your point about changing the language at runtime. However, my confusion stems from the fact that when the semantic has been hard-coded to be **Force Left-to-Right**, there should never be a case when the entry begins from the right. 
Am I missing something?

**Comment by riazhazan** [comment]
@xornorik still when the UI layout is RTL the SVPinView also mirroring, I mean the entry starts from right to left.

**Comment by xornorik** [comment]
I've added some logic in the latest version (v1.0.9) to fix this issue. Since I'm unable to recreate this at my end, could someone here confirm and close if it has indeed been fixed. 
Thank you.
