### ISSUE TITLE
always crash when using xcode 11.3, ios 13

### ISSUE THREAD

**Issue by adika-juniarsa** [xornorik/SVPinView#32]
halo help me , when i'm using this always crash on this line
`let textField = cell.viewWithTag(100) as! SVPinField`

**Comment by ChetanRajagiri** [comment]
try making it SVPinView

**Comment by xornorik** [comment]
Hi @adika-juniarsa, could you help me with recreating this issue? I was able to run in on Xcode 11.3 without any issues or crashes.

**Comment by xornorik** [comment]
Related to #41 and #49 
Fixed in **v1.0.9**
