### ISSUE TITLE
Pin Secure Delay

### ISSUE THREAD

**Issue by msbouchedid** [xornorik/SVPinView#40]
There is a delay of pin entries being secure when typing fast

**Comment by xornorik** [comment]
Hi @msbouchedid, this was intended behaviour to enable the user to have a brief glimpse at what was entered. 

I will make this a configurable field in the next release to suit your requirement.

**Comment by Sydney-o9** [comment]
@xornorik I have put a PR for this https://github.com/xornorik/SVPinView/pull/42 :)
