### ISSUE TITLE
when input secret start with index of 2, it will wrong.

### ISSUE THREAD

**Issue by llyouss** [xornorik/SVPinView#43]
// store text
        let text =  textField.text ?? ""
        let passwordIndex = index - 1
        if password.count > (passwordIndex) {
            // delete if space
            password[passwordIndex] = text == " " ? "" : text
        } else {
            **//it is wrong, it should input to  the index it should be.
            password.append(text)**
        }
        validateAndSendCallback()

**Comment by xornorik** [comment]
@llyouss 
Thank you for reporting this! 
Would you be able to check if this is relevant in the current version (1.0.9) as well? I was unable to get any unexpected behaviour.
