### ISSUE TITLE
How do you change PIN styling without clearing it first?

### ISSUE THREAD

**Issue by kosakoytim** [xornorik/SVPinView#44]
I have a case where i need to change my PIN style text color, underline color when the PIN input is invalid. I can't seem to do this without calling `pin.clearPin()` which will reload the view and clear all the input. Is there another way to do this?
Thanks

**Comment by xornorik** [comment]
There is a way in which you can do this, although it's a little ugly. 

The *didChangeCallback* gives you the pin that has been entered so far, this can be stored on the presenting layer (ViewController). You can then set the error styling, call *clearPin()* and follow it up by pasting the partial (or complete) pin using the *pastePin* method. 

The pasting will have to be delayed by a small offset in order for the view to have time to render itself before the pin is copied (hence ugly 😅). 

![errorState](https://user-images.githubusercontent.com/21356007/82984247-6359bb00-a00f-11ea-953a-87d08b520d99.gif)

```
pinView.textColor = .red
pinView.activeBorderLineColor = .red
pinView.borderLineColor = .red
pinView.becomeFirstResponderAtIndex = tempPinStore.count
clearPin()
DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
    self.pinView.pastePin(pin: self.tempPinStore)
}
```

Thanks for sharing your use-case, will try and improve on the way this is handled. 
Do let me know if this resolves your problem.

**Comment by kosakoytim** [comment]
I actually tried a similar method earlier, but got an error because i didn't add a delay for the rendering. This will solve for now, thanks!

**Comment by xornorik** [comment]
@kosakoytim 
I have added a completionHandler for the *clearPin* method in the latest release.
