### ISSUE TITLE
2 advices of SVPinView

### ISSUE THREAD

**Issue by ganweiming** [xornorik/SVPinView#46]
1.hope to provide milliseconds property to set secure text after a bit, some time we don't need delay  show secure text
2.when press delete key of keyboard wanna delete previous char or not just move the cursor to the text field
thanks

**Comment by xornorik** [comment]
@ganweiming Thank you for your feedback. 😄  
> 1.hope to provide milliseconds property to set secure text after a bit, some time we don't need delay show secure text

Agreed. Will include this in the upcoming release. 

> 2.when press delete key of keyboard wanna delete previous char or not just move the cursor to the text field

How would the user be able to delete the character in that textfield if the delete button would only shift the cursor?

**Comment by ganweiming** [comment]
@xornorik thanks for your reply
about point 2 is a case for payment scene, user should't touch the textfield, just press keyboard to input the password, i think maybe can provide a mode to clear the box when textfield focused, For reference only.

**Comment by xornorik** [comment]
@ganweiming 
I have added a property called *deleteButtonAction*, which has 3 options. 
I think the **.moveToPreviousAndDelete** option might be what you had in mind. 
Hope this helps. 
Thanks!
