### ISSUE TITLE
getting issue while installing pod 

### ISSUE THREAD

**Issue by premkumarsepuri** [xornorik/SVPinView#47]
Specs satisfying the `SVPinView` dependency were found, but they required a higher minimum deployment target. please help . thank you

**Comment by xornorik** [comment]
Hi @premkumarsepuri, 
The deployment target for SVPinView is 9.0 and the Swift version is 5.0. 
You will need to uncomment ```platform :ios, '9.0'``` in your podfile. 

If this doesn't fix the issue, could you give me some more details on how you've tried to install it. I will try and recreate it at my end.

Thanks.
