### ISSUE TITLE
Not always override character if focus a pinView

### ISSUE THREAD

**Issue by lfongaroScp** [xornorik/SVPinView#48]
Hi;
Thanks for your work.
I wrap your view in a SwiftUI app.

In this app I see an odd behavior. If the user tap a single pinView in the left half of the view it can prevent the overwrite of the existing character. 

I attach two screenshot to explain better myself. In the first (indicator is on the left) if the user digit a new character then the old one is not overwrite, in the second it will be overwrite.
![wrong](https://user-images.githubusercontent.com/13518686/87028869-8dda8e80-c1df-11ea-9051-8ff93391e32f.png)
Notice the indicator on the left side of the char. 

![right](https://user-images.githubusercontent.com/13518686/87028971-b2cf0180-c1df-11ea-9e37-9a6ec3908539.png)
notice the indicator on the right side of the char. In this case work

**Comment by xornorik** [comment]
@lfongaroScp I'm glad you found this useful. 
Thank you for reporting the issue and your detailed explanation. I was able to recreate it and will fix it in the upcoming release.
