### ISSUE TITLE
Install Manually Crashes  on starting 

### ISSUE THREAD

**Issue by PrashantKT** [xornorik/SVPinView#49]
I have copy source folder into xcode project 
and then in my XIB added View  of subclass  SVPinView

added required properties and crashes on starting 

 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'the cell returned from -collectionView:cellForItemAtIndexPath: does not have a reuseIdentifier - cells must be retrieved by calling -dequeueReusableCellWithReuseIdentifier:forIndexPath:'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3cf0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ba89b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e3cc88 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff258b8bd2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff484367de -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 1277
	5   UIKitCore                           0x00007fff484362db -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:] + 31
	6   UIKitCore                           0x00007fff4843bb7b -[UICollectionView _updateVisibleCellsNow:] + 6402
	7   UIKitCore                           0x00007fff48440cca -[UICollectionView layoutSubviews] + 351
	8   UIKitCore                           0x00007fff49193678 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2478
	9   QuartzCore                          0x00007fff2b4c6398 -[CALayer layoutSublayers] + 255
	10  QuartzCore                          0x00007fff2b4cc523 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 523
	11  QuartzCore                          0x00007fff2b4d7bba _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 80
	12  QuartzCore                          0x00007fff2b420c04 _ZN2CA7Context18commit_transactionEPNS_11TransactionEd + 324
	13  QuartzCore                          0x00007fff2b4545ef _ZN2CA11Transaction6commitEv + 649
	14  UIKitCore                           0x00007fff48ca3747 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 81
	15  CoreFoundation                      0x00007fff23da0b5c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	16  CoreFoundation                      0x00007fff23da0253 __CFRunLoopDoBlocks + 195
	17  CoreFoundation                      0x00007fff23d9b043 __CFRunLoopRun + 995
	18  CoreFoundation                      0x00007fff23d9a944 CFRunLoopRunSpecific + 404
	19  GraphicsServices                    0x00007fff38ba6c1a GSEventRunModal + 139
	20  UIKitCore                           0x00007fff48c8b9ec UIApplicationMain + 1605
	21  App                             0x000000010b0027bb main + 75
	22  libdyld.dylib                       0x00007fff51a231fd start + 1
	23  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by PrashantKT** [comment]
Fixed 

On cell, we need to choose SVPinField again so it uses it from current target 

<img width="1120" alt="Screenshot 2020-07-15 at 5 34 26 PM" src="https://user-images.githubusercontent.com/35359315/87543039-9dffdb80-c6c1-11ea-925b-642dbb427547.png">

**Comment by xornorik** [comment]
Yes, I'll include this change in the next release so it is easier to pull the files from the source folder. 
Thanks for identifying it 👍
