### ISSUE TITLE
Does this library have support for the new OneTimePasscode introduced in iOS 12 ?

### ISSUE THREAD

**Issue by subinrevi** [xornorik/SVPinView#51]
Is there any way we can achieve this with this framework. Since iOS 12 has introduced this feature.

`static let oneTimeCode: UITextContentType`

**Comment by xornorik** [comment]
Hey @subinrevi 
It does indeed. The PinView has a property `isContentTypeOneTimeCode` which when set to true (true by default), activates the oneTimePasscode feature.
