### ISSUE TITLE
Autofill doesn't work at iPhone 6s - iOS 13.7

### ISSUE THREAD

**Issue by razor313** [xornorik/SVPinView#53]
I have an issue with iPhone 6s - iOS 13.7. Autofill doesn't appear on the top of the official keyboard of the iOS.
It seems this behavior is occurred just on iPhone 6 - 6s
Here a buch of my code:

`    lazy var verificationTextField: SVPinView = {
        let textField = SVPinView()
        textField.translatesAutoresizingMaskIntoConstraints = false
        textField.pinLength = 6
        textField.interSpace = 5
        textField.borderLineColor = .red
        textField.activeBorderLineColor = .black
        textField.borderLineThickness = 1
        textField.activeBorderLineThickness = 3
        textField.becomeFirstResponderAtIndex = 0
        textField.keyboardType = .numberPad
        textField.isContentTypeOneTimeCode = true
        textField.style = .underline
        return textField
    }()`

**Comment by ErAshu** [comment]
is this working or not? Autofill is necessary in my case. Pls revert.

**Comment by xornorik** [comment]
@razor313 Are you still facing this issue? I was unable to replicate it on the simulator. I've since updated my Xcode and it doesn't seem to be allowing me to download iOS 13.7. I'll have to downgrade to an older version of Xcode to test. 
Will do so if you can confirm you're still facing the issue. 
Thank you for reporting it.

**Comment by razor313** [comment]
@ErAshu It works like a charm.

**Comment by razor313** [comment]
@xornorik As far as I know, it works on iOS 13.x without any problems as well as iOS 14.0.

**Comment by xornorik** [comment]
@razor313 That's great! 
Thanks for confirming! 
Closing this issue.

**Comment by lunavo** [comment]
I have issue Autofill doesn't appear with iPhone 7Plus, os 15.7.1. I put pinView.isContentTypeOneTimeCode = true to SVPinViewExample but still not working.
