### ISSUE TITLE
Crash while opening SVPinCell

### ISSUE THREAD

**Issue by NohaMohamed** [xornorik/SVPinView#55]
Unknown class SVPinField in Interface Builder file.

Assertion failure in -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:], 

 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'the cell returned from -collectionView:cellForItemAtIndexPath: does not have a reuseIdentifier - cells must be retrieved by calling -dequeueReusableCellWithReuseIdentifier:forIndexPath:'

**Comment by xornorik** [comment]
@NohaMohamed 
Did you use CocoaPods/Carthage for installing or did you manually drag the files into your project?

**Comment by xornorik** [comment]
@NohaMohamed 
I've put out a fix for this in v1.0.11. If you're still using this, could you please confirm if this has been fixed? 
Thank you.

**Comment by lightonalan** [comment]
Hi,
I'm using CocoaPods, and also got the same issue. However it's gone after I called clearPin function on viewDidLoad. Just note for someone facing this error
