### ISSUE TITLE
It's broken on Right to Left Languages

### ISSUE THREAD

**Issue by omaarr90** [xornorik/SVPinView#6]
Pin entry should always be left to right

**Comment by xornorik** [comment]
Hi @omaarr90, are you saying you would like the pinView to support Right to left entry?

**Comment by oenama** [comment]
@xornorik no , it does support pinView, he's saying that it should not , cuz pin entry should always be from left to right

**Comment by omaarr90** [comment]
When the device language is Arabic which is an RTL language. The pin entry goes right to left which is wrong. 

In all languages numbers Always read left to right. 

You can test by editing the Scheme and chosing launch options and select Arabic is the language to start with.

**Comment by xornorik** [comment]
@omaarr90 Okay thanks! will investigate.

**Comment by MVakas** [comment]
Hi any update on this? I'm facing the same problem.

**Comment by yarakhater** [comment]
any updates?

**Comment by sanket003** [comment]
Can you please provide update on this?

**Comment by apphardtask** [comment]
And no update till now!!!
