### ISSUE TITLE
PinView crashes on iPhone SE 2nd Generation

### ISSUE THREAD

**Issue by AnkurLahiry** [xornorik/SVPinView#69]
Hello there, 

I have been using SVPinView, and thanks for the wonderful library. I have been facing a crash on the latest release `1.0.11`.

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'the cell returned from -collectionView:cellForItemAtIndexPath: does not have a reuseIdentifier - cells must be retrieved by calling -dequeueReusableCellWithReuseIdentifier:forIndexPath:'
```

In other issues, it is referenced that it was a problem of copying cocoa pod. 

Here is my podfile
![Screenshot 2022-03-13 at 11 47 00 AM](https://user-images.githubusercontent.com/35650095/158046887-ce21d91b-3550-4985-9f56-134451df1b6f.png)

Here is my xib file

![Screenshot 2022-03-13 at 11 43 38 AM](https://user-images.githubusercontent.com/35650095/158046831-2bd65465-cb45-4a23-b47d-a012d1448fe0.png)

Thanks in advance

**Comment by AnkurLahiry** [comment]
The issue behind that, I tried to capture the keyboard notifications `KeyboardWillShow`, `KeyboardWillhide` before awaking the PinView. Receiving the events after awaking solved the issue

**Comment by blavkjay** [comment]
@AnkurLahiry please how did you go about this?
