### ISSUE TITLE
clearPin() crash on iOS 10.3.3

### ISSUE THREAD

**Issue by himanshuNetsol** [xornorik/SVPinView#7]
In iOS version 10.3.3 of iPad, it **crashes** . It is bcoz **cell.viewWithTag** unable to **typecast** view into **SVPinFeild**.
Can i get any help on this??
Attached the crash below.
![screen shot 2018-06-20 at 1 36 37 pm](https://user-images.githubusercontent.com/37396038/41645585-07d9cb92-748f-11e8-8e7e-3c994e05fd58.png)

**Comment by xornorik** [comment]
Sure, could you help me out with the error logs? Is it crashing consistently?

**Comment by himanshuNetsol** [comment]
Yes.. Only on iOS version 10.3.3, it is crashing consistently, with error:
EXC_BREAKPOINT (code=EXC_ARM_BREAKPOINT, subcode=0xe7ffdefe)

**Comment by himanshuNetsol** [comment]
Yeah Sure... Value for **indexPath.row = 0**

**Comment by xornorik** [comment]
@himanshuNetsol I'm not able to recreate the issue, I'll add some additional checks on the clearPin method and make some other changes that I think might be contributing to the issue and push code. Could you check for it then and revert?

**Comment by himanshuNetsol** [comment]
For sure.. Thanks 👍

**Comment by himanshuNetsol** [comment]
Hi.
Any updates on this ?? When will u be pushing the updated code??

**Comment by xornorik** [comment]
Hey, Yes I've solved it. Will be making a release in about 8 hours with the fix.

**Comment by xornorik** [comment]
@himanshuNetsol Could you confirm if this has been fixed?

**Comment by himanshuNetsol** [comment]
Hi..
Yes.. The issue is fixed now. ThankYou Very Much :-)
