### ISSUE TITLE
becomeFirstResponder() doesn't work

### ISSUE THREAD

**Issue by M3Rocket** [xornorik/SVPinView#9]
I have put the field and wish it to be the FirstReponder on a view. But nothing I do can make the field become focussed as the first responder and bring up the keyboard? I have to click on the field to bring up the keyboard.

**Comment by xornorik** [comment]
Had originally intended it to be made the first responder only on tap of the field. But you're right, this would be a good feature addition. Will update shortly. Thanks!

**Comment by xornorik** [comment]
@M3Rocket, have added a property - `becomeFirstResponderAtIndex`, which sets the field at the specified index to become the first responder.

**Comment by M3Rocket** [comment]
That is awesome! I will check it out. Thank You!

**Comment by dhaval00700** [comment]
I have put the field and wish it to be the FirstReponder on a "viewOtP.becomeFirstResponderAtIndex "
it's show nil

**Comment by dhaval00700** [comment]
> becomeFirstResponderAtIndex
i have use this Property but i found log is "nil"
